---
- name: Bootstrap ND server
  become_user: steam
  hosts: nd
  vars:
    sourcemod_host: http://www.sourcemod.net/smdrop/1.8/
    sourcemod_file: sourcemod-1.8.0-git5909-linux.tar.gz
    metamod_host: http://mirror.pointysoftware.net/alliedmodders/
    metamod_file: mmsource-1.10.6-linux.tar.gz
    steamcmd: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz


  tasks:
    - name: prepare dirs
      file: path={{ item }} state=directory owner=steam
      with_items:
        - /home/steam/tmp/nd
        - /home/steam/bin
        - /home/steam/.steam/sdk32

    - name: get Steamcmd
      get_url: dest=/home/steam/bin/ url={{ steamcmd }}

    - name: get Metamod
      get_url: dest=/home/steam/tmp/ url={{ metamod_host }}{{ metamod_file }}

    - name: get SourceMod
      get_url: dest=/home/steam/tmp/ url={{ sourcemod_host }}{{ sourcemod_file }}

    - name: install Steamcmd
      unarchive: src=/home/steam/bin/steamcmd_linux.tar.gz dest=/home/steam/bin

    - name: install ND server
      register: nd_downloaded
      shell: /home/steam/bin/steamcmd.sh +login anonymous +force_install_dir /home/steam/nd +app_update 111710 validate +quit
      ignore_errors: yes
      retries: 2
      # until: nd_downloaded|success
      # this has to run twice, idk why .(

    - name: install ND server II
      register: nd_downloaded
      shell: /home/steam/bin/steamcmd.sh +login anonymous +force_install_dir /home/steam/nd +app_update 111710 validate +quit
      ignore_errors: yes
      retries: 2
      # until: nd_downloaded|success
      # this has to run twice, idk why .(

    - name: copy steamclient.so
      shell: cp /home/steam/bin/linux32/steamclient.so /home/steam/.steam/sdk32/steamclient.so
               creates=/home/steam/.steam/sdk32/steamclient.so

    - name: install Metamod
      shell: tar xzf /home/steam/tmp/{{ metamod_file }} -C /home/steam/nd/nucleardawn
      # TODO - if file not exists

    - name: install Sourcemod
      shell: tar xzf /home/steam/tmp/{{ sourcemod_file }} -C /home/steam/nd/nucleardawn
      # TODO - if file not exists

    - name: start server
      shell: circusctl start ndserver
